Repository GoormProject/walkit-server, pull requests merged in 2025-07, with the labels that each got.

#5 chore: 테스트용 DB 생성 SQL 추가
  docker-compose.local.yml
  initdb/02-create-test-db.sql
Labels: chore

#6 feat/#2: 회원 관련 엔티티 추가
  initdb/02-create-test-db.sql
  src/main/java/life/walkit/server/global/BaseEntity.java
  src/main/java/life/walkit/server/global/config/JpaConfig.java
  src/main/java/life/walkit/server/global/error/core/BaseException.java
  src/main/java/life/walkit/server/global/error/core/ErrorCode.java
  src/main/java/life/walkit/server/global/error/core/ErrorResponse.java
  src/main/java/life/walkit/server/member/entity/Friend.java
  src/main/java/life/walkit/server/member/entity/Member.java
  src/main/java/life/walkit/server/member/entity/enums/FriendStatus.java
  src/main/java/life/walkit/server/member/entity/enums/MemberRole.java
  src/main/java/life/walkit/server/member/entity/enums/MemberStatus.java
  src/main/java/life/walkit/server/member/error/MemberException.java
  src/main/java/life/walkit/server/member/error/enums/MemberErrorCode.java
Labels: feature

#8 Feat/#4: 날씨 엔티티 추가
  src/main/java/life/walkit/server/weather/controller/WeatherController.java
  src/main/java/life/walkit/server/weather/entity/EupMyeonDong.java
  src/main/java/life/walkit/server/weather/entity/Sido.java
  src/main/java/life/walkit/server/weather/entity/Sigungu.java
  src/main/java/life/walkit/server/weather/entity/Weather.java
  src/main/java/life/walkit/server/weather/repository/WeatherRepository.java
  src/main/java/life/walkit/server/weather/service/WeatherService.java
Labels: feature

#10 Feat/#3: 산책로, 산책기록, 리뷰 엔티티 구현
  src/main/java/life/walkit/server/review/entity/Review.java
  src/main/java/life/walkit/server/review/error/enums/ReviewErrorCode.java
  src/main/java/life/walkit/server/review/repository/ReviewRepository.java
  src/main/java/life/walkit/server/trail/entity/Trail.java
  src/main/java/life/walkit/server/trail/entity/TrailImage.java
  src/main/java/life/walkit/server/trail/error/enums/TrailErrorCode.java
  src/main/java/life/walkit/server/trail/repository/TrailRepository.java
  src/main/java/life/walkit/server/walk/entity/Walk.java
  src/main/java/life/walkit/server/walk/entity/WalkingSession.java
  src/main/java/life/walkit/server/walk/entity/enums/EventType.java
  src/main/java/life/walkit/server/walk/error/enums/WalkErrorCode.java
  src/main/java/life/walkit/server/walk/repository/WalkRepository.java
  src/main/java/life/walkit/server/walk/repository/WalkingSessionRepository.java
Labels: feature

#13 Refactor/#12: member 관련 엔티티 연결
  src/main/java/life/walkit/server/review/entity/Review.java
  src/main/java/life/walkit/server/review/error/enums/ReviewErrorCode.java
  src/main/java/life/walkit/server/trail/entity/Trail.java
  src/main/java/life/walkit/server/trail/error/enums/TrailErrorCode.java
  src/main/java/life/walkit/server/walk/entity/Walk.java
  src/main/java/life/walkit/server/walk/error/enums/WalkErrorCode.java
Labels: refactor

#18 Feature/#11: 산책기록, 산책기록중간세션, 산책로, 산책로 이미지, 리뷰 테이블 레포지스토리 구현 및 테스트
  src/main/java/life/walkit/server/trail/entity/Trail.java
  src/main/java/life/walkit/server/trail/entity/TrailImage.java
  src/main/java/life/walkit/server/trail/repository/TrailImageRepository.java
  src/main/java/life/walkit/server/trail/repository/TrailRepository.java
  src/main/java/life/walkit/server/walk/entity/Walk.java
  src/main/java/life/walkit/server/walk/entity/WalkingSession.java
  src/main/java/life/walkit/server/walk/repository/WalkRepository.java
  src/main/java/life/walkit/server/walk/repository/WalkingSessionRepository.java
  src/test/java/life/walkit/server/global/factory/GlobalTestFactory.java
  src/test/java/life/walkit/server/member/factory/MemberTestFactory.java
  src/test/java/life/walkit/server/member/repository/FriendRepositoryTest.java
  src/test/java/life/walkit/server/member/repository/MemberRepositoryTest.java
  src/test/java/life/walkit/server/trail/repository/TrailImageRepositoryTest.java
  src/test/java/life/walkit/server/trail/repository/TrailRepositoryTest.java
  src/test/java/life/walkit/server/walk/repository/WalkRepositoryTest.java
  src/test/java/life/walkit/server/walk/repository/WalkingSessionRepositoryTest.java
Labels: feature

#15 Feat/#14: 날씨 Repository 구현 및 테스트 작성
  src/main/java/life/walkit/server/weather/repository/WeatherRepository.java
  src/test/java/life/walkit/server/weather/factory/WeatherTestFactory.java
  src/test/java/life/walkit/server/weather/repository/WeatherRepositoryTest.java
Labels: feature

#23 Feat/#22: BaseResponse, GlobalExceptionHandler 추가
  src/main/java/life/walkit/server/global/error/core/ErrorResponse.java
  src/main/java/life/walkit/server/global/error/handler/GlobalErrorCode.java
  src/main/java/life/walkit/server/global/error/handler/GlobalExceptionHandler.java
  src/main/java/life/walkit/server/global/response/BaseResponse.java
  src/main/java/life/walkit/server/global/response/Response.java
Labels: feature

#29 Feat/#24: 산책 경로 엔티티 반영
  src/main/java/life/walkit/server/path/entity/Path.java
  src/main/java/life/walkit/server/path/repository/PathRepository.java
  src/main/java/life/walkit/server/trail/entity/Trail.java
  src/main/java/life/walkit/server/walk/entity/Walk.java
  src/test/java/life/walkit/server/global/factory/GlobalTestFactory.java
  src/test/java/life/walkit/server/trail/repository/TrailImageRepositoryTest.java
  src/test/java/life/walkit/server/trail/repository/TrailRepositoryTest.java
  src/test/java/life/walkit/server/walk/repository/WalkRepositoryTest.java
  src/test/java/life/walkit/server/walk/repository/WalkingSessionRepositoryTest.java
Labels: feature, refactor

#28 Feat/#26: 친구요청 엔티티 추가 및 ERD 구조 변경, 관련 로직 수정
  src/main/java/life/walkit/server/friend/entity/Friend.java
  src/main/java/life/walkit/server/friend/entity/FriendStatus.java
  src/main/java/life/walkit/server/friend/repository/FriendRepository.java
  src/main/java/life/walkit/server/friendrequest/entity/FriendRequest.java
  src/main/java/life/walkit/server/friendrequest/entity/FriendRequestStatus.java
  src/main/java/life/walkit/server/friendrequest/repository/FriendRequestRepository.java
  src/main/java/life/walkit/server/member/repository/MemberRepository.java
  src/test/java/life/walkit/server/friendrequest/repository/FriendRequestRepositoryTest.java
  src/test/java/life/walkit/server/global/factory/GlobalTestFactory.java
  src/test/java/life/walkit/server/member/repository/FriendRepositoryTest.java
Labels: feature, refactor

#31 Fix/#30: Enum 클래스 import 경로 수정
  src/main/java/life/walkit/server/friendrequest/entity/FriendRequest.java
  src/main/java/life/walkit/server/friendrequest/entity/enums/FriendRequestStatus.java
  src/main/java/life/walkit/server/friendrequest/repository/FriendRequestRepository.java
  src/test/java/life/walkit/server/friendrequest/repository/FriendRequestRepositoryTest.java
Labels: bug

#32 Feat/#27: 토큰 재발급 기능 추가
  src/main/java/life/walkit/server/auth/controller/AuthController.java
  src/main/java/life/walkit/server/auth/dto/CustomMemberDetails.java
  src/main/java/life/walkit/server/auth/dto/enums/AuthResponse.java
  src/main/java/life/walkit/server/auth/error/enums/JwtTokenErrorCode.java
  src/main/java/life/walkit/server/auth/handler/CustomAuthenticationEntryPoint.java
  src/main/java/life/walkit/server/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/life/walkit/server/auth/jwt/JwtTokenIssuer.java
  src/main/java/life/walkit/server/auth/jwt/JwtTokenParser.java
  src/main/java/life/walkit/server/auth/repository/JwtTokenRepository.java
  src/main/java/life/walkit/server/auth/repository/RedisKeyValueRepository.java
  src/main/java/life/walkit/server/auth/resolver/CustomAuthorizationRequestResolver.java
  src/main/java/life/walkit/server/global/config/SecurityConfig.java
Labels: feature

#35 Chore/#34: S3 파일 업로드 설정
  build.gradle
  src/main/java/life/walkit/server/global/config/S3Config.java
Labels: chore

#36 Feat/#17: 친구 및 친구 요청 패키지 통합 및 친구 요청 기능 구현
  src/main/java/life/walkit/server/friend/controller/FriendController.java
  src/main/java/life/walkit/server/friend/dto/FriendRequestResponseDTO.java
  src/main/java/life/walkit/server/friend/entity/Friend.java
  src/main/java/life/walkit/server/friend/entity/FriendRequest.java
  src/main/java/life/walkit/server/friend/enums/FriendRequestResponse.java
  src/main/java/life/walkit/server/friend/enums/FriendRequestStatus.java
  src/main/java/life/walkit/server/friend/enums/FriendResponse.java
  src/main/java/life/walkit/server/friend/error/FriendErrorCode.java
  src/main/java/life/walkit/server/friend/error/FriendException.java
  src/main/java/life/walkit/server/friend/repository/FriendRepository.java
  src/main/java/life/walkit/server/friend/repository/FriendRequestRepository.java
  src/main/java/life/walkit/server/friend/service/FriendService.java
  src/main/java/life/walkit/server/member/entity/Member.java
  src/main/java/life/walkit/server/member/error/enums/MemberErrorCode.java
  src/test/java/life/walkit/server/friend/repository/FriendRepositoryTest.java
  src/test/java/life/walkit/server/friend/service/FriendServiceTest.java
  src/test/java/life/walkit/server/friendrequest/repository/FriendRequestRepositoryTest.java
  src/test/java/life/walkit/server/global/factory/GlobalTestFactory.java
Labels: feature

#40 Feat/#33: 프로필 수정 기능 추가
  src/main/java/life/walkit/server/global/util/S3Utils.java
  src/main/java/life/walkit/server/member/controller/MemberController.java
  src/main/java/life/walkit/server/member/dto/ProfileRequest.java
  src/main/java/life/walkit/server/member/dto/ProfileResponse.java
  src/main/java/life/walkit/server/member/dto/enums/MemberResponse.java
  src/main/java/life/walkit/server/member/entity/Member.java
  src/main/java/life/walkit/server/member/entity/ProfileImage.java
  src/main/java/life/walkit/server/member/error/enums/MemberErrorCode.java
  src/main/java/life/walkit/server/member/repository/ProfileImageRepository.java
  src/main/java/life/walkit/server/member/service/MemberService.java
  src/test/java/life/walkit/server/member/service/MemberServiceTest.java
Labels: feature

#43 Feat/#41: 내 정보 조회 기능 추가
  src/main/java/life/walkit/server/member/controller/MemberController.java
  src/main/java/life/walkit/server/member/dto/enums/MemberResponse.java
  src/main/java/life/walkit/server/member/service/MemberService.java
  src/test/java/life/walkit/server/member/service/MemberServiceTest.java
Labels: feature

#49 Feat/#42: 친구 요청 수신 목록 조회 기능 구현
  src/main/java/life/walkit/server/friend/controller/FriendController.java
  src/main/java/life/walkit/server/friend/dto/ReceivedFriendResponse.java
  src/main/java/life/walkit/server/friend/service/FriendService.java
  src/test/java/life/walkit/server/friend/service/FriendServiceTest.java
Labels: feature

#58 Feat/#51: 친구 요청 거절 기능 구현
  src/main/java/life/walkit/server/friend/controller/FriendController.java
  src/main/java/life/walkit/server/friend/service/FriendService.java
  src/test/java/life/walkit/server/friend/service/FriendServiceTest.java
Labels: feature

#61 chore: Github Actions CI 설정
  .github/workflows/gradle.yml
Labels: chore

#62 Feat/#59: 친구 목록 조회 기능 구현
  src/main/java/life/walkit/server/friend/controller/FriendController.java
  src/main/java/life/walkit/server/friend/dto/FriendRequestApprovedResponse.java
  src/main/java/life/walkit/server/friend/dto/FriendResponseDTO.java
  src/main/java/life/walkit/server/friend/service/FriendService.java
  src/test/java/life/walkit/server/friend/service/FriendServiceTest.java
Labels: feature

#64 Feat/#63: 친구 삭제 기능 구현
  src/main/java/life/walkit/server/friend/controller/FriendController.java
  src/main/java/life/walkit/server/friend/repository/FriendRepository.java
  src/main/java/life/walkit/server/friend/service/FriendService.java
  src/test/java/life/walkit/server/friend/service/FriendServiceTest.java
Labels: feature

#68 Feat/#21: 산책 기록 API 구현
  src/main/java/life/walkit/server/walk/controller/WalkController.java
  src/main/java/life/walkit/server/walk/dto/enums/WalkResponse.java
  src/main/java/life/walkit/server/walk/dto/request/WalkRequest.java
  src/main/java/life/walkit/server/walk/dto/response/WalkCreateResponse.java
  src/main/java/life/walkit/server/walk/dto/response/WalkDeleteResponse.java
  src/main/java/life/walkit/server/walk/dto/response/WalkEventResponse.java
  src/main/java/life/walkit/server/walk/dto/response/WalkListResponse.java
  src/main/java/life/walkit/server/walk/entity/Walk.java
  src/main/java/life/walkit/server/walk/entity/WalkingSession.java
  src/main/java/life/walkit/server/walk/error/enums/WalkErrorCode.java
  src/main/java/life/walkit/server/walk/error/enums/WalkException.java
  src/main/java/life/walkit/server/walk/repository/WalkingSessionRepository.java
  src/main/java/life/walkit/server/walk/service/WalkService.java
  src/test/java/life/walkit/server/walk/service/WalkServiceTest.java
Labels: feature
