Repository GoormProject/walkit-server, pull requests merged in 2025-08, with the labels that each got.

#74 Refactor/#69: 행정구역 엔티티 분리 및 데이터 로드
  src/main/java/life/walkit/server/WalkitServerApplication.java
  src/main/java/life/walkit/server/weather/config/AdminAreaInitializer.java
  src/main/java/life/walkit/server/weather/dto/AdminAreaDto.java
  src/main/java/life/walkit/server/weather/entity/AdminArea.java
  src/main/java/life/walkit/server/weather/entity/Weather.java
  src/main/java/life/walkit/server/weather/repository/AdminAreaRepository.java
  src/main/java/life/walkit/server/weather/repository/WeatherRepository.java
  src/main/resources/static/admin_area.json
  src/test/java/life/walkit/server/weather/factory/WeatherTestFactory.java
  src/test/java/life/walkit/server/weather/repository/WeatherRepositoryTest.java
Labels: refactor

#70 Feat/#60: 활동 상태에 따른 친구 목록 조회 기능 구현
  src/main/java/life/walkit/server/friend/controller/FriendController.java
  src/main/java/life/walkit/server/friend/dto/FriendResponseDTO.java
  src/main/java/life/walkit/server/friend/repository/FriendRepository.java
  src/main/java/life/walkit/server/friend/service/FriendService.java
  src/test/java/life/walkit/server/friend/service/FriendServiceTest.java
Labels: feature

#77 bug/#76: Path null 허용
  src/main/java/life/walkit/server/path/entity/Path.java
  src/main/java/life/walkit/server/walk/service/WalkService.java
Labels: bug

#78 bug/#76: Builder Default 값 설정
  gradlew
  src/main/java/life/walkit/server/walk/entity/Walk.java
  src/main/java/life/walkit/server/walk/service/WalkService.java
  src/test/java/life/walkit/server/walk/service/WalkServiceTest.java
Labels: bug

#79 Bug/#76: CascadeType 설정
  src/main/java/life/walkit/server/walk/dto/request/WalkRequest.java
  src/main/java/life/walkit/server/walk/entity/Walk.java
  src/main/java/life/walkit/server/walk/service/WalkService.java
Labels: bug

#84 Feat/67: 날씨 API 연동
  build.gradle
  src/main/java/life/walkit/server/global/config/SecurityConfig.java
  src/main/java/life/walkit/server/global/config/WebClientConfig.java
  src/main/java/life/walkit/server/global/error/core/BaseException.java
  src/main/java/life/walkit/server/global/ratelimiter/ApiRateLimiter.java
  src/main/java/life/walkit/server/weather/config/WeatherApiProperties.java
  src/main/java/life/walkit/server/weather/controller/WeatherController.java
  src/main/java/life/walkit/server/weather/dto/ClothResponse.java
  src/main/java/life/walkit/server/weather/dto/WeatherDto.java
  src/main/java/life/walkit/server/weather/dto/WeatherForecastResponseDto.java
  src/main/java/life/walkit/server/weather/dto/WeatherLocationRequestDto.java
  src/main/java/life/walkit/server/weather/dto/enums/WeatherResponse.java
  src/main/java/life/walkit/server/weather/entity/Weather.java
  src/main/java/life/walkit/server/weather/error/WeatherException.java
  src/main/java/life/walkit/server/weather/error/enums/WeatherErrorCode.java
  src/main/java/life/walkit/server/weather/model/ClothingRule.java
  src/main/java/life/walkit/server/weather/model/enums/Clouds.java
  src/main/java/life/walkit/server/weather/model/enums/Night.java
  src/main/java/life/walkit/server/weather/model/enums/Precipitation.java
  src/main/java/life/walkit/server/weather/model/enums/Wind.java
  src/main/java/life/walkit/server/weather/repository/AdminAreaRepository.java
  src/main/java/life/walkit/server/weather/repository/WeatherRepository.java
  src/main/java/life/walkit/server/weather/service/ClothingService.java
  src/main/java/life/walkit/server/weather/service/WeatherService.java
  src/main/java/life/walkit/server/weather/utils/WeatherCodeMapper.java
  src/test/java/life/walkit/server/weather/factory/WeatherTestFactory.java
  src/test/java/life/walkit/server/weather/repository/WeatherRepositoryTest.java
  src/test/java/life/walkit/server/weather/service/WeatherServiceTest.java
Labels: feature

#88 Fix/#87: 프로필 수정 기능 오류 수정
  src/main/java/life/walkit/server/member/controller/MemberController.java
Labels: bug

#86 Feat/#83: 친구 위치 조회 기능 구현
  src/main/java/life/walkit/server/friend/controller/FriendController.java
  src/main/java/life/walkit/server/friend/dto/FriendLocationResponseDTO.java
  src/main/java/life/walkit/server/friend/enums/FriendResponse.java
  src/main/java/life/walkit/server/friend/service/FriendService.java
Labels: feature

#90 Feat/89: 산책로 리뷰 기능 구현
  src/main/java/life/walkit/server/review/controller/ReviewController.java
  src/main/java/life/walkit/server/review/dto/ReviewListResponse.java
  src/main/java/life/walkit/server/review/dto/ReviewResponse.java
  src/main/java/life/walkit/server/review/dto/enums/TrailReviewResponse.java
  src/main/java/life/walkit/server/review/dto/request/ReviewRequest.java
  src/main/java/life/walkit/server/review/dto/request/ReviewUpdateRequest.java
  src/main/java/life/walkit/server/review/entity/Review.java
  src/main/java/life/walkit/server/review/error/ReviewException.java
  src/main/java/life/walkit/server/review/error/enums/ReviewErrorCode.java
  src/main/java/life/walkit/server/review/repository/ReviewRepository.java
  src/main/java/life/walkit/server/review/service/ReviewService.java
  src/main/java/life/walkit/server/trail/error/enums/TrailErrorCode.java
Labels: feature

#94 Bug/#93: ci/cd error
  .github/workflows/deploy.yml
Labels: bug

#97 chore/#96: ci/cd yml 디렉토리 경로 생성
  .github/workflows/deploy.yml
Labels: bug

#99 bug/#9: CD 테스트 제외 빌드
  .github/workflows/deploy.yml
Labels: bug

#101 feat: Docker 파일 생성
  .github/workflows/deploy.yml
  Dockerfile
Labels: bug

#103 bug/#94: ci/cd 오타
  .github/workflows/deploy.yml
Labels: bug

#105 fix: 서버 시작 300초로 늘리기
  appspec.yml
Labels: bug

#121 Feat/#118: ReceivedFriendResponse에 친구요청 ID 필드 추가
  src/main/java/life/walkit/server/friend/dto/ReceivedFriendResponse.java
  src/main/java/life/walkit/server/friend/service/FriendService.java
  src/test/java/life/walkit/server/friend/service/FriendServiceTest.java
Labels: feature, refactor

#126 Feat/125: 산책로 조회시 평균 평점 조회 구현
  src/main/java/life/walkit/server/review/dto/ReviewStats.java
  src/main/java/life/walkit/server/review/entity/Review.java
  src/main/java/life/walkit/server/review/repository/ReviewRepository.java
  src/main/java/life/walkit/server/trail/dto/response/TrailDetailResponse.java
  src/main/java/life/walkit/server/trail/dto/response/TrailListResponse.java
  src/main/java/life/walkit/server/trail/service/TrailService.java
Labels: feature
